# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etud/Documents/stage/aux-armes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etud/Documents/stage/aux-armes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etud/Documents/stage/aux-armes/CMakeFiles /home/etud/Documents/stage/aux-armes//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etud/Documents/stage/aux-armes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Aux_armes

# Build rule for target.
Aux_armes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aux_armes
.PHONY : Aux_armes

# fast build rule for target.
Aux_armes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/build
.PHONY : Aux_armes/fast

carte.o: carte.cpp.o

.PHONY : carte.o

# target to build an object file
carte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/carte.cpp.o
.PHONY : carte.cpp.o

carte.i: carte.cpp.i

.PHONY : carte.i

# target to preprocess a source file
carte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/carte.cpp.i
.PHONY : carte.cpp.i

carte.s: carte.cpp.s

.PHONY : carte.s

# target to generate assembly for a file
carte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/carte.cpp.s
.PHONY : carte.cpp.s

jeu.o: jeu.cpp.o

.PHONY : jeu.o

# target to build an object file
jeu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/jeu.cpp.o
.PHONY : jeu.cpp.o

jeu.i: jeu.cpp.i

.PHONY : jeu.i

# target to preprocess a source file
jeu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/jeu.cpp.i
.PHONY : jeu.cpp.i

jeu.s: jeu.cpp.s

.PHONY : jeu.s

# target to generate assembly for a file
jeu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/jeu.cpp.s
.PHONY : jeu.cpp.s

joueur.o: joueur.cpp.o

.PHONY : joueur.o

# target to build an object file
joueur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/joueur.cpp.o
.PHONY : joueur.cpp.o

joueur.i: joueur.cpp.i

.PHONY : joueur.i

# target to preprocess a source file
joueur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/joueur.cpp.i
.PHONY : joueur.cpp.i

joueur.s: joueur.cpp.s

.PHONY : joueur.s

# target to generate assembly for a file
joueur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/joueur.cpp.s
.PHONY : joueur.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aux_armes.dir/build.make CMakeFiles/Aux_armes.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Aux_armes"
	@echo "... carte.o"
	@echo "... carte.i"
	@echo "... carte.s"
	@echo "... jeu.o"
	@echo "... jeu.i"
	@echo "... jeu.s"
	@echo "... joueur.o"
	@echo "... joueur.i"
	@echo "... joueur.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

